<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Class mentor_entity
 *
 * @package    local_mentor_specialization
 * @copyright  2020 Edunao SAS (contact@edunao.com)
 * @author     adrien <adrien@edunao.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_mentor_specialization;

defined('MOODLE_INTERNAL') || die();

require_once($CFG->dirroot . '/local/mentor_core/classes/model/entity.php');
require_once($CFG->dirroot . '/local/mentor_specialization/classes/database_interface.php');

class mentor_entity extends \local_mentor_core\entity {

    /**
     * @var int[]
     */
    public $regions;

    private $dbinterfacementor;

    private $sirhlist;

    public $ishidden;

    /**
     * mentor_entity constructor.
     *
     * @param entity|int $entityorid
     * @throws \dml_exception
     * @throws \moodle_exception
     */
    public function __construct($entityorid) {
        parent::__construct($entityorid);

        $this->dbinterfacementor = database_interface::get_instance();
        $this->regions           = explode(',', $this->get_regions_id());

        $this->ishidden = $this->is_hidden();
    }

    /**
     * Check if the entity is hidden
     *
     * @return int 1 for hidden, 0 if visible
     * @throws \dml_exception
     */
    public function is_hidden() {
        $option = $this->dbinterfacementor->get_category_option($this->id, 'hidden');
        if ($option) {
            return $option->value;
        }

        return 0;
    }

    /**
     * Get entity regions id
     *
     * @return string list of regions separated by commas
     * @throws \dml_exception
     */
    private function get_regions_id() {
        $option = $this->dbinterfacementor->get_category_option($this->id, 'regionid');
        if ($option && $this->is_main_entity()) {
            return $option->value;
        }

        return 0;
    }

    /**
     * Get the list of sirh
     *
     * @return array
     * @throws \dml_exception
     */
    public function get_sirh_list($refresh = false) {
        if (empty($this->sirhlist) || $refresh) {
            $option = $this->dbinterfacementor->get_category_option($this->id, 'sirhlist');

            if ($option && $option->value && $this->is_main_entity()) {
                $this->sirhlist = explode(',', $option->value);
            } else {
                $this->sirhlist = [];
            }
        }

        return $this->sirhlist;
    }

    /**
     * Override the entity update process
     *
     * @param \stdClass $data
     * @param null $mform
     * @return bool|void
     * @throws \coding_exception
     * @throws \dml_exception
     * @throws \moodle_exception
     */
    public function update($data, $mform = null) {

        parent::update($data, $mform);

        if ($this->is_main_entity()) {
            // Update entity region.
            if (isset($data->regions)) {
                $this->update_regions($data->regions);
            }

            // Update entity sirh list.
            if (is_siteadmin() && isset($data->sirhlist)) {
                $this->update_sirh_list($data->sirhlist);
            }
        }

        // Update hidden field.
        if (is_siteadmin() && isset($data->hidden)) {
            $this->update_visibility($data->hidden);
        }

        return true;
    }

    public function get_presentation_page_course() {
        // TODO: Change the autogenerated stub.
        return parent::get_presentation_page_course();
    }

    /**
     * Update the visibility of the entity
     *
     * @param int $hidden 1 to hide the entity
     * @return void
     * @throws \dml_exception
     */
    public function update_visibility($hidden) {
        $this->ishidden = $hidden;
        $this->dbinterfacementor->update_entity_visibility($this->id, $hidden);
    }

    /**
     * Update sirh list
     *
     * @param string|array $sirhlist
     * @throws \dml_exception
     */
    public function update_sirh_list($sirhlist) {
        if ($this->is_main_entity()) {
            $this->sirhlist = is_array($sirhlist) ? $sirhlist : explode(',', $sirhlist);

            $this->dbinterfacementor->update_entity_sirh_list($this->id, $this->sirhlist);
        }
    }

    /**
     * Update the entity region
     *
     * @param int|array $regionsid
     * @throws \coding_exception
     * @throws \dml_exception
     * @throws \moodle_exception
     */
    public function update_regions($regionsid) {
        global $CFG;
        require_once($CFG->dirroot . '/local/user/lib.php');
        require_once($CFG->dirroot . '/local/mentor_core/api/profile.php');

        if (!is_array($regionsid)) {
            $regionsid = [$regionsid];
        }

        $this->dbinterfacementor->update_entity_regions($this->id, $regionsid);
        $this->regions = $regionsid;

        // Manage cohort members.
        $oldusers = $this->get_members();
        $newusers = $this->dbinterfacementor->get_users_by_regions($regionsid);

        // Get users by entity.
        $entityusers = \local_mentor_core\profile_api::get_users_by_mainentity($this->name);

        $newusers = array_merge($newusers, $entityusers);

        // Determine members to add and to remove.
        $userstoadd    = array_diff_key($newusers, $oldusers);
        $userstoremove = array_diff_key($oldusers, $newusers);

        // Remove old members.
        foreach ($userstoremove as $usertoremove) {
            $this->remove_member($usertoremove);
        }

        // Add new members.
        foreach ($userstoadd as $usertoadd) {
            $this->add_member($usertoadd);
        }
    }

    /**
     * Override the entity get_form_data method
     *
     * @return \stdClass
     * @throws \coding_exception
     * @throws \dml_exception
     */
    public function get_form_data() {
        $entityobj = parent::get_form_data();

        // Add specific fields for main entity only.
        if ($this->is_main_entity()) {
            // Add the region id to the form data.
            $entityobj->regions  = $this->regions;
            $entityobj->sirhlist = $this->get_sirh_list();
        }

        $entityobj->hidden = $this->is_hidden();

        return $entityobj;
    }

    /**
     * Get manager role
     *
     * @return \stdClass
     * @throws \dml_exception
     */
    public function get_manager_role() {
        return $this->dbinterface->get_role_by_name('admindedie');
    }

    /**
     * Get entity trainings
     *
     * @return \stdClass[]
     * @throws \dml_exception
     */
    public function get_trainings() {
        $db = database_interface::get_instance();
        return $db->get_trainings_by_entity_id($this->id, false);
    }
}
